[phases.setup]
nixPkgs = ["php", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.curl", "php81Extensions.fileinfo"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php init.php",
    "echo 'Build completed successfully'"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ." 